name: Test Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 8
      - name: Client Build
        run: |
          cd client
          pnpm install
          pnpm run build
      - name: Library Build
        run: |
          cd lib
          pnpm install
          pnpm run lint
      - name: Server Build
        run: |
          cd legacy-ts-server
          pnpm install
          pnpm run build
