# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy Server
on:
  push:
    branches:
      - [main, dev]  # temporarily enabling dev for debugging
jobs:
  deploy:
    defaults:
      run:
        working-directory: server
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: ./mvnw package
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
