name: Test Frontend

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    defaults:
        run:
          working-directory: client 

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - run: pnpm install
      - run: pnpm run build
